[build-system]
requires = ["setuptools<81", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "ati"
version = "0.1.0"
description = "Automated Training Interface"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["pydantic-settings>=2.14.1"]

[project.scripts]
template_ati_plug = "ati.__init__:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["ati*"]

[tool.uv]
package = true
